version: '3.8'
services:
  tis-bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      # Можно убрать TIS_LOGIN / TIS_PASSWORD — они теперь в БД
    volumes:
      - ./data:/app/data          # ← важно для сохранения БД
    restart: unless-stopped